/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Name
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setIconImage();
        setTitle("Main page");
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));

    }

    int id;
    String uname;
    String usertype;

    public Main(int id, String username, String utype) {
        setIconImage();
        setTitle("Main page");
        initComponents();
        this.uname = username;
        jLabel1.setText(uname);

        this.usertype = utype;
        jLabel2.setText(utype);

        this.id = id;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        accountbutton = new javax.swing.JButton();
        subjectbutton = new javax.swing.JButton();
        exambutton = new javax.swing.JButton();
        studentbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        teacherbutton = new javax.swing.JButton();
        markbutton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        classbutton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setForeground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        accountbutton.setText("ACCOUNT");
        accountbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountbuttonMouseClicked(evt);
            }
        });
        accountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(accountbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 46));

        subjectbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        subjectbutton.setText("SUBJECT");
        subjectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(subjectbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 46));

        exambutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        exambutton.setText("EXAM");
        exambutton.setBorder(null);
        exambutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exambutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exambuttonActionPerformed(evt);
            }
        });
        jPanel3.add(exambutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 160, 46));

        studentbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        studentbutton.setText("STUDENT");
        studentbutton.setBorder(null);
        studentbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(studentbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 160, 46));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MAIN MENU");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 61));

        logoutbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        logoutbutton.setText("LOGOUT");
        logoutbutton.setBorder(null);
        logoutbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbuttonMouseClicked(evt);
            }
        });
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 160, 46));

        teacherbutton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        teacherbutton.setText("TEACHER");
        teacherbutton.setBorder(null);
        teacherbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(teacherbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 160, 46));

        markbutton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        markbutton1.setText("MARK");
        markbutton1.setBorder(null);
        markbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        markbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markbutton1ActionPerformed(evt);
            }
        });
        jPanel3.add(markbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 160, 46));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 60));

        classbutton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        classbutton1.setText("CLASS");
        classbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbutton1ActionPerformed(evt);
            }
        });
        jPanel3.add(classbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, 46));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("USERNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 14, 96, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("USER TYPE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 50, 93, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 6, 80, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("USER TYPE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 50, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("SCHOOL MANAGEMENT SYSTEM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 34, 370, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 181, 394, -1));

        jLabel7.setText("Developed by:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Naveenkumar J");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 0, 590, 670));

        jMenu1.setText("About Project");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        About a = new About();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void subjectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectbuttonActionPerformed
        // TODO add your handling code here:
        Subject s = new Subject(id, uname, usertype);
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_subjectbuttonActionPerformed

    private void accountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountbuttonActionPerformed
        // TODO add your handling code here:
//        User u = new User(id, uname, usertype);
//        u.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_accountbuttonActionPerformed

    private void exambuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exambuttonActionPerformed
        // TODO add your handling code here:
        Exam e = new Exam(id, uname, usertype);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exambuttonActionPerformed

    private void studentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbuttonActionPerformed
        // TODO add your handling code here:
        new Student(id, uname, usertype).setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_studentbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void teacherbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherbuttonActionPerformed
        // TODO add your handling code here:
        Teacher t = new Teacher(id, uname, usertype);
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_teacherbuttonActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URI("https://github.com/naveenkumar-j"));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void logoutbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbuttonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutbuttonMouseClicked

    private void markbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markbutton1ActionPerformed
        // TODO add your handling code here:
        Mark m = new Mark(id, uname, usertype);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_markbutton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MouseClicked

    private void classbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbutton1ActionPerformed
        // TODO add your handling code here:
        Classes c = new Classes(id, uname, usertype);
        c.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_classbutton1ActionPerformed

    private void accountbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMouseClicked
        // TODO add your handling code here:
        User u = new User(id, uname, usertype);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_accountbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountbutton;
    private javax.swing.JButton classbutton1;
    private javax.swing.JButton exambutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton markbutton1;
    private javax.swing.JButton studentbutton;
    private javax.swing.JButton subjectbutton;
    private javax.swing.JButton teacherbutton;
    // End of variables declaration//GEN-END:variables
}
